imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }

parameters:
    locale: fr
    files_directory: '%kernel.root_dir%/../web/uploads'
    locales: fr|en|es|de|it

framework:
    secret: '%secret%'
    router:
        resource: '%kernel.project_dir%/app/config/routing.yml'
        strict_requirements: ~
    form: ~
    csrf_protection: ~
    validation: { enable_annotations: true }
    default_locale: '%locale%'
    trusted_hosts: ~
    session:
        handler_id: session.handler.native_file
        save_path: '%kernel.project_dir%/var/sessions/%kernel.environment%'
    fragments: ~
    http_method_override: true
    assets:
        json_manifest_path: '%kernel.project_dir%/web/assets/manifest.json'
    php_errors:
        log: true
    translator:
        fallbacks: ['fr']
        paths: ['%kernel.project_dir%/translations']
    serializer:
        enabled: true

translation:
    locales: ['fr', 'en', 'es', 'de', 'it']
    configs:
        app:
            dirs: ["%kernel.root_dir%/Resources/views", "%kernel.project_dir%/src"]
            output_dir: "%kernel.project_dir%/translations"
            excluded_dirs: [cache, data, logs]
    webui:
        enabled: true

# Twig Configuration
twig:
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'

# Doctrine Configuration
doctrine:
    dbal:
        driver: pdo_mysql
        host: '%database_host%'
        port: '%database_port%'
        dbname: '%database_name%'
        user: '%database_user%'
        password: '%database_password%'
        charset: UTF8

    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true
        mappings:
           gedmo_loggable:
                type: annotation
                prefix: Gedmo\Loggable\Entity
                dir: "%kernel.project_dir%/vendor/gedmo/doctrine-extensions/lib/Gedmo/Loggable/Entity"
                alias: GedmoLoggable
                is_bundle: false
stof_doctrine_extensions:
    default_locale: en_US
    orm:
        default:
            sortable: true

# Swiftmailer Configuration
swiftmailer:
    transport: '%mailer_transport%'
    host: '%mailer_host%'
    username: '%mailer_user%'
    password: '%mailer_password%'
    spool: { type: memory }

sensio_framework_extra:
    request: { converters: true }
fos_rest:
    body_converter:
        enabled: true
    view:
        formats: { json: true, xml: false, rss: false }
        view_response_listener: true
    serializer:
        serialize_null: true
    format_listener:
        rules:
        - { path: '^/api/file', priorities: [ 'text/html', '*/*'], fallback_format: html, prefer_extension: true }
        - { path: '^/api', priorities: ['json'], fallback_format: 'json' }
        - { path: '^/', priorities: [ 'html', '*/*'], fallback_format: ~, prefer_extension: true }
cmf_routing:
    chain:
        routers_by_id:
            router.default: 200
            cmf_routing.dynamic_router: 100
    dynamic:
        enabled: true
        persistence:
            orm:
                enabled: true
        generic_controller: AppBundle:Default:showPage

nelmio_cors:
    paths:
      '^/(login|logout)':
          allow_origin: ['*']
          allow_headers: ['Content-Type']
          allow_methods: ['OPTIONS', 'POST', 'GET']
          allow_credentials: true
          max_age: 3600
