imports:
    - { resource: config.yml }
    - { resource: services.yml }

framework:
    router:
        resource: '%kernel.project_dir%/app/config/routing_dev.yml'
        strict_requirements: true
    profiler: { only_exceptions: false }

web_profiler:
    toolbar: true
    intercept_redirects: false

monolog:
    handlers:
        main:
            type: stream
            path: '%kernel.logs_dir%/%kernel.environment%.log'
            level: debug
            channels: ['!event']
        console:
            type: console
            process_psr_3_messages: false
            channels: ['!event', '!doctrine', '!console']
        server_log:
            type: server_log
            process_psr_3_messages: false
            host: 127.0.0.1:9911
swiftmailer:
    transport: smtp
    host: 2525
    username: user
    password: password
    spool: { type: memory }
doctrine:
    dbal:
        driver: pdo_sqlite
        dbname: '%database_name%'
        password: '%database_password%'
        charset: UTF8
        path: '%kernel.project_dir%/var/data/data.sqlite'
        # driver: pdo_mysql
        # host: '%database_host%'
        # port: '%database_port%'
        # dbname: '%database_name%'
        # user: '%database_user%'
        # password: '%database_password%'
        # charset: UTF8

translation:
    symfony_profiler:
        enabled: true