parameters:
  role_hierarchy:
    ROLE_ADMIN: ROLE_USER
    ROLE_ADMIN_SPEAKER:
      - ROLE_ADMIN_SPEAKER_VIEW
      - ROLE_ADMIN_SPEAKER_CREATE
      - ROLE_ADMIN_SPEAKER_EDIT
      - ROLE_ADMIN_SPEAKER_DELETE
    ROLE_ADMIN_NEWS:
      - ROLE_ADMIN_NEWS_VIEW
      - ROLE_ADMIN_NEWS_CREATE
      - ROLE_ADMIN_NEWS_EDIT
      - ROLE_ADMIN_NEWS_DELETE
    ROLE_ADMIN_PAGE:
      - ROLE_ADMIN_PAGE_VIEW
      - ROLE_ADMIN_PAGE_CREATE
      - ROLE_ADMIN_PAGE_EDIT
      - ROLE_ADMIN_PAGE_DELETE
    ROLE_ADMIN_USER:
      - ROLE_ADMIN_USER_VIEW
      - ROLE_ADMIN_USER_CREATE
      - ROLE_ADMIN_USER_EDIT
      - ROLE_ADMIN_USER_DELETE

    ROLE_ADMIN_CONTENT_ASSOCIATION:
      - ROLE_ADMIN_CONTENT_ASSOCIATION_VIEW
      - ROLE_ADMIN_CONTENT_ASSOCIATION_CREATE
      - ROLE_ADMIN_CONTENT_ASSOCIATION_EDIT
      - ROLE_ADMIN_CONTENT_ASSOCIATION_DELETE
    ROLE_ADMIN_CONTENT_EDITION:
      - ROLE_ADMIN_CONTENT_EDITION_VIEW
      - ROLE_ADMIN_CONTENT_EDITION_CREATE
      - ROLE_ADMIN_CONTENT_EDITION_EDIT
      - ROLE_ADMIN_CONTENT_EDITION_DELETE
    ROLE_ADMIN_CONTENT_ASSOCIATION_VIEW:
      - ROLE_ADMIN_CONTENT_VIEW
    ROLE_ADMIN_CONTENT_EDITION_VIEW:
      - ROLE_ADMIN_CONTENT_VIEW
    ROLE_ADMIN_CONTENT_ASSOCIATION_EDIT:
      - ROLE_ADMIN_CONTENT_EDIT
    ROLE_ADMIN_CONTENT_EDITION_EDIT:
      - ROLE_ADMIN_CONTENT_EDIT
    ROLE_ADMIN_HOME:
      - ROLE_ADMIN_HOME_VIEW
      - ROLE_ADMIN_HOME_CREATE
      - ROLE_ADMIN_HOME_EDIT
      - ROLE_ADMIN_HOME_DELETE

    ROLE_ADMIN_ASSOCIATION:
      - ROLE_ADMIN
      - ROLE_ADMIN_NEWS
      - ROLE_ADMIN_CONTENT_ASSOCIATION
      - ROLE_ADMIN_HOME
    ROLE_ADMIN_EDITION:
      - ROLE_ADMIN
      - ROLE_ADMIN_NEWS
      - ROLE_ADMIN_CONTENT_EDITION
    ROLE_SUPER_ADMIN:
      - ROLE_ADMIN
      - ROLE_ADMIN_USER
      - ROLE_ADMIN_SPEAKER
      - ROLE_ADMIN_ASSOCIATION
      - ROLE_ADMIN_EDITION
      - ROLE_ADMIN_PAGE
