app:
    resource: '@AppBundle/Controller/'
    type: annotation
    schemes: [http]
rest_api:
    type: rest
    prefix: /api
    resource: '@AppBundle/Resources/config/rest_routes.yml'
    schemes: [http]
file:
    resource: "@AppBundle/Controller/FileController.php"
    type:     annotation
    schemes: [http]
