security:
    providers:
        in_memory:
            memory:
                users:
                    admin:
                        password: '%admin_password%'
                        roles: 'ROLE_SUPER_ADMIN'

        legacy_db_provider:
            entity:
                class: AppBundle:Contact
                property: username
        shop_db_provider:
            entity:
                class: AppBundle:Client
                property: email
    role_hierarchy:
        ROLE_ADMIN: ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN
    encoders:
        AppBundle\Entity\Contact: bcrypt
        AppBundle\Entity\Client: bcrypt
        Symfony\Component\Security\Core\User\User: bcrypt

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        shop:
            pattern: ^/([a-z]{2,3}\/(cart|shop|order)|shop/(login|register|password-request))
            provider: shop_db_provider
            anonymous: ~
            json_login:
                check_path: /shop/login
        main:
            pattern: ^/
            provider: legacy_db_provider
            anonymous: ~
            json_login:
                check_path: /login
            form_login:
                login_path: login-form
                check_path: login-form
            logout:
                path:   /logout
                invalidate_session: true
                target: /

    access_control:
        - { path: ^/api, role: ROLE_ADMIN}
        - { path: ^/crud, role: ROLE_ADMIN}
        - { path: ^/admin/_trans, role: ROLE_ADMIN}
