security:
    providers:
        in_memory:
            memory:
                users:
                    admin:
                        password: admin
                        roles: 'ROLE_ADMIN'

        # our_db_provider:
        #     entity:
        #         class: AppBundle:User

    encoders:
        Symfony\Component\Security\Core\User\User: plaintext

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: ~
            json_login:
                check_path: /login
            logout:
                path:   /logout
                invalidate_session: true
                target: /login

    access_control:
        - { path: ^/api, role: ROLE_ADMIN}
