page:
    type: rest
    name_prefix: api_page_
    resource: AppBundle\Controller\PageController
speaker:
    type: rest
    name_prefix: api_speaker_
    resource: AppBundle\Controller\SpeakerController
