page:
    type: rest
    name_prefix: api_page
    resource: AppBundle\Controller\PageController
speaker:
    type: rest
    name_prefix: api_speaker
    resource: AppBundle\Controller\SpeakerController
