calendar:
    type: rest
    name_prefix: api_calendar_
    resource: AppBundle\Controller\CalendarController
default:
    type: rest
    name_prefix: api_default_
    resource: AppBundle\Controller\DefaultController
order:
    type: rest
    name_prefix: api_order_
    resource: AppBundle\Controller\OrderController
shop_security:
    type: rest
    name_prefix: api_shop_security_
    resource: AppBundle\Controller\ShopSecurityController
gift:
    type: rest
    name_prefix: api_gift_
    resource: AppBundle\Controller\GiftController
cart:
    type: rest
    name_prefix: api_cart_
    resource: AppBundle\Controller\CartController